---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ pvc_name | default('ocsci-pvc') }}
  namespace: {{ cluster_namespace | default('openshift-storage') }}
spec:
  accessModes:
  - {{ access_mode | default('ReadWriteOnce') }}
  resources:
    requests:
      storage: {{ pvc_size | default('5Gi') }}
  storageClassName: {{ sc_name | default('ocsci-storageclass') }}