---
apiVersion: v1
kind: Pod
metadata:
  name: {{ pod_name | default('ocsci-pod') }}
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: ocsci-pvc
readOnly: false