apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocsci-pvc
  namespace: openshift-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocsci-storageclass
