apiVersion: v1
kind: Pod
metadata:
  name: ocsci-pod
readOnly: false
spec:
  containers:
  - image: nginx
    name: web-server
    volumeMounts:
    - mountPath: /var/lib/www/html
      name: mypvc
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: ocsci-pvc
